---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alden392/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo.svg $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
