---
deployment:
  tasks:
    # Reset any uncommitted changes in the server repository
    - cd /home/alden392/repositories/portfolioREAL
    - git reset --hard HEAD
    - git clean -fd
    - git pull origin main
    
    # Deploy the files
    - export DEPLOYPATH=/home/alden392/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
