---
deployment:
  tasks:
    # Simple deployment without heavy dependencies
    - export DEPLOYPATH=/home/alden392/public_html/
    
    # Use system node (usually more reliable)
    - node --version
    - npm --version
    
    # Quick install without peer deps
    - npm install --production --no-optional
    
    # Build
    - npm run build
    
    # Deploy
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
