---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alden392/public_html/
    - /bin/npm install --production=false
    - /bin/npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
