---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alden392/public_html/
    - export NVM_DIR=$HOME/.nvm
    - source $NVM_DIR/nvm.sh
    - nvm install 18
    - nvm use 18
    - npm install
    - npm run build
    - find $DEPLOYPATH -mindepth 1 -delete
    - cp -R dist/* $DEPLOYPATH/
    - cp .htaccess $DEPLOYPATH/
